version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=False
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    restart: always
    networks:
      - open-webui-net

  ollama:
    image: ollama-custom
    container_name: ollama-cpu
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - open-webui-net

volumes:
  open-webui:
  ollama:

networks:
  open-webui-net:
    driver: bridge
